name: install dedalus 3
on:
  workflow_dispatch:

jobs:
  my-job:
    name: run the code
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: install virtualenv and activate
        run: sudo apt install python3-virtualenv; source python_env/bin/activate
#       - name: install Dedalus 3
#         run:  source installDedalus3.sh

