name: run without docker
on:
  workflow_dispatch:

jobs:
  my-job:
    name: run the code
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: activate conda
        run: conda activate
      - name: run the install script        
        run:  source installDedalus.sh

