name: install dedalus 3
on:
  workflow_dispatch:

jobs:
  my-job:
    name: run the code
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: install virtualenv and activate
        run:  sudo apt install python3-virtualenv
      - name: virtualenv --no-download python_env
        run:  virtualenv --no-download python_env
      - name: source python_env/bin/activate
        run:  source python_env/bin/activate
      - name: pip install --upgrade pip
        run:  pip install --upgrade pip
      - name: pip install cython xarray
        run:  pip install cython xarray
      - name: pip install pytest pytest-cov pytest-benchmar
        run:  pip install pytest pytest-cov pytest-benchmar
      - name: pip install pytest-parallel
        run:  pip install pytest-parallel
        

